// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/msg/FieldType.msg - do not modify

#include "Msgs/ROS2TDIFieldType.h"

#include "Kismet/GameplayStatics.h"

void UROS2TDIFieldTypeMsg::Init()
{
    type_description_interfaces__msg__FieldType__init(&field_type_msg);
}

void UROS2TDIFieldTypeMsg::Fini()
{
    type_description_interfaces__msg__FieldType__fini(&field_type_msg);
}

const rosidl_message_type_support_t* UROS2TDIFieldTypeMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(type_description_interfaces, msg, FieldType);
}

void UROS2TDIFieldTypeMsg::SetMsg(const FROSTDIFieldType& Inputs)
{
    Inputs.SetROS2(field_type_msg);
}

void UROS2TDIFieldTypeMsg::GetMsg(FROSTDIFieldType& Outputs) const
{
    Outputs.SetFromROS2(field_type_msg);
}

void* UROS2TDIFieldTypeMsg::Get()
{
    return &field_type_msg;
}

FString UROS2TDIFieldTypeMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
