// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/msg/KeyValue.msg - do not modify

#include "Msgs/ROS2TDIKeyValue.h"

#include "Kismet/GameplayStatics.h"

void UROS2TDIKeyValueMsg::Init()
{
    type_description_interfaces__msg__KeyValue__init(&key_value_msg);
}

void UROS2TDIKeyValueMsg::Fini()
{
    type_description_interfaces__msg__KeyValue__fini(&key_value_msg);
}

const rosidl_message_type_support_t* UROS2TDIKeyValueMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(type_description_interfaces, msg, KeyValue);
}

void UROS2TDIKeyValueMsg::SetMsg(const FROSTDIKeyValue& Inputs)
{
    Inputs.SetROS2(key_value_msg);
}

void UROS2TDIKeyValueMsg::GetMsg(FROSTDIKeyValue& Outputs) const
{
    Outputs.SetFromROS2(key_value_msg);
}

void* UROS2TDIKeyValueMsg::Get()
{
    return &key_value_msg;
}

FString UROS2TDIKeyValueMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
