// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from service_msgs/msg/ServiceEventInfo.msg - do not modify

#include "Msgs/ROS2ServiceEventInfo.h"

#include "Kismet/GameplayStatics.h"

void UROS2ServiceEventInfoMsg::Init()
{
    service_msgs__msg__ServiceEventInfo__init(&service_event_info_msg);
}

void UROS2ServiceEventInfoMsg::Fini()
{
    service_msgs__msg__ServiceEventInfo__fini(&service_event_info_msg);
}

const rosidl_message_type_support_t* UROS2ServiceEventInfoMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(service_msgs, msg, ServiceEventInfo);
}

void UROS2ServiceEventInfoMsg::SetMsg(const FROSServiceEventInfo& Inputs)
{
    Inputs.SetROS2(service_event_info_msg);
}

void UROS2ServiceEventInfoMsg::GetMsg(FROSServiceEventInfo& Outputs) const
{
    Outputs.SetFromROS2(service_event_info_msg);
}

void* UROS2ServiceEventInfoMsg::Get()
{
    return &service_event_info_msg;
}

FString UROS2ServiceEventInfoMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
