// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/msg/IndividualTypeDescription.msg - do not modify

#include "Msgs/ROS2TDIIndividualTypeDescription.h"

#include "Kismet/GameplayStatics.h"

void UROS2TDIIndividualTypeDescriptionMsg::Init()
{
    type_description_interfaces__msg__IndividualTypeDescription__init(&individual_type_description_msg);
}

void UROS2TDIIndividualTypeDescriptionMsg::Fini()
{
    type_description_interfaces__msg__IndividualTypeDescription__fini(&individual_type_description_msg);
}

const rosidl_message_type_support_t* UROS2TDIIndividualTypeDescriptionMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(type_description_interfaces, msg, IndividualTypeDescription);
}

void UROS2TDIIndividualTypeDescriptionMsg::SetMsg(const FROSTDIIndividualTypeDescription& Inputs)
{
    Inputs.SetROS2(individual_type_description_msg);
}

void UROS2TDIIndividualTypeDescriptionMsg::GetMsg(FROSTDIIndividualTypeDescription& Outputs) const
{
    Outputs.SetFromROS2(individual_type_description_msg);
}

void* UROS2TDIIndividualTypeDescriptionMsg::Get()
{
    return &individual_type_description_msg;
}

FString UROS2TDIIndividualTypeDescriptionMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
