// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/msg/Field.msg - do not modify

#include "Msgs/ROS2TDIField.h"

#include "Kismet/GameplayStatics.h"

void UROS2TDIFieldMsg::Init()
{
    type_description_interfaces__msg__Field__init(&field_msg);
}

void UROS2TDIFieldMsg::Fini()
{
    type_description_interfaces__msg__Field__fini(&field_msg);
}

const rosidl_message_type_support_t* UROS2TDIFieldMsg::GetTypeSupport() const
{
    return ROSIDL_GET_MSG_TYPE_SUPPORT(type_description_interfaces, msg, Field);
}

void UROS2TDIFieldMsg::SetMsg(const FROSTDIField& Inputs)
{
    Inputs.SetROS2(field_msg);
}

void UROS2TDIFieldMsg::GetMsg(FROSTDIField& Outputs) const
{
    Outputs.SetFromROS2(field_msg);
}

void* UROS2TDIFieldMsg::Get()
{
    return &field_msg;
}

FString UROS2TDIFieldMsg::MsgToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
