// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/msg/PolygonInstance.msg - do not modify

#include "Msgs/ROS2PolygonInstance.h"

#include "Kismet/GameplayStatics.h"



void UROS2PolygonInstanceMsg::Init()
{
	geometry_msgs__msg__PolygonInstance__init(&polygon_instance_msg);
}

void UROS2PolygonInstanceMsg::Fini()
{
	geometry_msgs__msg__PolygonInstance__fini(&polygon_instance_msg);
}

const rosidl_message_type_support_t* UROS2PolygonInstanceMsg::GetTypeSupport() const
{
	return ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, PolygonInstance);
}

void UROS2PolygonInstanceMsg::SetMsg(const FROSPolygonInstance& Inputs)
{
    Inputs.SetROS2(polygon_instance_msg);
}

void UROS2PolygonInstanceMsg::GetMsg(FROSPolygonInstance& Outputs) const
{
    Outputs.SetFromROS2(polygon_instance_msg);
}

void* UROS2PolygonInstanceMsg::Get()
{
	return &polygon_instance_msg;
}

FString UROS2PolygonInstanceMsg::MsgToString() const
{
    /* TODO: Fill here */
	checkNoEntry();
	return FString();
}