// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/srv/GetTypeDescription.srv - do not modify

#include "Srvs/ROS2TDIGetTypeDescription.h"

const rosidl_service_type_support_t* UROS2TDIGetTypeDescriptionSrv::GetTypeSupport() const
{
    return ROSIDL_GET_SRV_TYPE_SUPPORT(type_description_interfaces, srv, GetTypeDescription);
}

void UROS2TDIGetTypeDescriptionSrv::Init()
{
    type_description_interfaces__srv__GetTypeDescription_Request__init(&GetTypeDescription_req);
    type_description_interfaces__srv__GetTypeDescription_Response__init(&GetTypeDescription_res);
}

void UROS2TDIGetTypeDescriptionSrv::Fini()
{
    type_description_interfaces__srv__GetTypeDescription_Request__fini(&GetTypeDescription_req);
    type_description_interfaces__srv__GetTypeDescription_Response__fini(&GetTypeDescription_res);
}

void UROS2TDIGetTypeDescriptionSrv::SetRequest(const FROSTDIGetTypeDescriptionReq& Request)
{
    Request.SetROS2(GetTypeDescription_req);
}

void UROS2TDIGetTypeDescriptionSrv::GetRequest(FROSTDIGetTypeDescriptionReq& Request) const
{
    Request.SetFromROS2(GetTypeDescription_req);
}

void UROS2TDIGetTypeDescriptionSrv::SetResponse(const FROSTDIGetTypeDescriptionRes& Response)
{
    Response.SetROS2(GetTypeDescription_res);
}

void UROS2TDIGetTypeDescriptionSrv::GetResponse(FROSTDIGetTypeDescriptionRes& Response) const
{
    Response.SetFromROS2(GetTypeDescription_res);
}

void* UROS2TDIGetTypeDescriptionSrv::GetRequest()
{
    return &GetTypeDescription_req;
}

void* UROS2TDIGetTypeDescriptionSrv::GetResponse()
{
    return &GetTypeDescription_res;
}

FString UROS2TDIGetTypeDescriptionSrv::SrvRequestToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}

FString UROS2TDIGetTypeDescriptionSrv::SrvResponseToString() const
{
    /* TODO: Fill here */
    checkNoEntry();
    return FString();
}
