// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from geometry_msgs/msg/PolygonInstance.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "geometry_msgs/msg/polygon_instance.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2Polygon.h"


// Generated
#include "ROS2PolygonInstance.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSPolygonInstance
{
	GENERATED_BODY()

public:
	

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FROSPolygon Polygon;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int64 Id = 0;

	

	FROSPolygonInstance()
	{
		
	}

	void SetFromROS2(const geometry_msgs__msg__PolygonInstance& in_ros_data)
	{
    	Polygon.SetFromROS2(in_ros_data.polygon);

		Id = in_ros_data.id;

		
	}

	void SetROS2(geometry_msgs__msg__PolygonInstance& out_ros_data) const
	{
    	Polygon.SetROS2(out_ros_data.polygon);

		out_ros_data.id = Id;

		
	}
};

UCLASS()
class RCLUE_API UROS2PolygonInstanceMsg : public UROS2GenericMsg
{
	GENERATED_BODY()

public:
	virtual void Init() override;
	virtual void Fini() override;

	virtual const rosidl_message_type_support_t* GetTypeSupport() const override;
	
  	UFUNCTION(BlueprintCallable)
	void SetMsg(const FROSPolygonInstance& Input);
	
  	UFUNCTION(BlueprintCallable)
	void GetMsg(FROSPolygonInstance& Output) const;
	
	virtual void* Get() override;

	


private:
	virtual FString MsgToString() const override;

	geometry_msgs__msg__PolygonInstance polygon_instance_msg;
};