// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/msg/IndividualTypeDescription.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "type_description_interfaces/msg/individual_type_description.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)
#include "Msgs/ROS2TDIField.h"
#include "type_description_interfaces/msg/detail/field__functions.h"

// Generated
#include "ROS2TDIIndividualTypeDescription.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSTDIIndividualTypeDescription
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString TypeName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FROSTDIField> Fields;

    FROSTDIIndividualTypeDescription()
    {
    }

    void SetFromROS2(const type_description_interfaces__msg__IndividualTypeDescription& in_ros_data)
    {
        TypeName = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.type_name);

        UROS2Utils::SequenceROSToUEArray<type_description_interfaces__msg__Field, FROSTDIField>(
            in_ros_data.fields.data, Fields, in_ros_data.fields.size);
    }

    void SetROS2(type_description_interfaces__msg__IndividualTypeDescription& out_ros_data) const
    {
        UROS2Utils::StringUEToROS(TypeName, out_ros_data.type_name);

        if (out_ros_data.fields.data)
        {
            type_description_interfaces__msg__Field__Sequence__fini(&out_ros_data.fields);
        }
        if (!type_description_interfaces__msg__Field__Sequence__init(&out_ros_data.fields, Fields.Num()))
        {
            UE_LOG_WITH_INFO(LogTemp, Error, TEXT("failed to create array for field out_ros_data.fields  "));
        }
        UROS2Utils::ArrayUEToROSSequence<type_description_interfaces__msg__Field, FROSTDIField>(
            Fields, out_ros_data.fields.data, Fields.Num());
    }
};

UCLASS()
class RCLUE_API UROS2TDIIndividualTypeDescriptionMsg : public UROS2GenericMsg
{
    GENERATED_BODY()

public:
    virtual void Init() override;
    virtual void Fini() override;

    virtual const rosidl_message_type_support_t* GetTypeSupport() const override;

    UFUNCTION(BlueprintCallable)
    void SetMsg(const FROSTDIIndividualTypeDescription& Input);

    UFUNCTION(BlueprintCallable)
    void GetMsg(FROSTDIIndividualTypeDescription& Output) const;

    virtual void* Get() override;

private:
    virtual FString MsgToString() const override;

    type_description_interfaces__msg__IndividualTypeDescription individual_type_description_msg;
};
