// Copyright 2021-2024 Rapyuta Robotics Co., Ltd.
// This code has been autogenerated from type_description_interfaces/msg/TypeSource.msg - do not modify

#pragma once

// UE
#include "CoreMinimal.h"

// ROS
#include "type_description_interfaces/msg/type_source.h"

// rclUE
#include "Msgs/ROS2GenericMsg.h"
#include "rclcUtilities.h"

// Generated Msg/Srv/Action(can be empty)

// Generated
#include "ROS2TDITypeSource.generated.h"

USTRUCT(Blueprintable)
struct RCLUE_API FROSTDITypeSource
{
    GENERATED_BODY()

public:
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString TypeName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Encoding;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString RawFileContents;

    FROSTDITypeSource()
    {
    }

    void SetFromROS2(const type_description_interfaces__msg__TypeSource& in_ros_data)
    {
        TypeName = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.type_name);

        Encoding = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.encoding);

        RawFileContents = UROS2Utils::StringROSToUE<rosidl_runtime_c__String>(in_ros_data.raw_file_contents);
    }

    void SetROS2(type_description_interfaces__msg__TypeSource& out_ros_data) const
    {
        UROS2Utils::StringUEToROS(TypeName, out_ros_data.type_name);

        UROS2Utils::StringUEToROS(Encoding, out_ros_data.encoding);

        UROS2Utils::StringUEToROS(RawFileContents, out_ros_data.raw_file_contents);
    }
};

UCLASS()
class RCLUE_API UROS2TDITypeSourceMsg : public UROS2GenericMsg
{
    GENERATED_BODY()

public:
    virtual void Init() override;
    virtual void Fini() override;

    virtual const rosidl_message_type_support_t* GetTypeSupport() const override;

    UFUNCTION(BlueprintCallable)
    void SetMsg(const FROSTDITypeSource& Input);

    UFUNCTION(BlueprintCallable)
    void GetMsg(FROSTDITypeSource& Output) const;

    virtual void* Get() override;

private:
    virtual FString MsgToString() const override;

    type_description_interfaces__msg__TypeSource type_source_msg;
};
